import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "utils/trpc";
import styles from "./index.module.css";

const Home: NextPage = () => {
  const { data, refetch } = trpc.useQuery(["presentation.getAll"]);

  const createPresentation = trpc.useMutation(["presentation.create"]);
  const deletePresentation = trpc.useMutation(["presentation.delete"]);

  const addPresentation = async () => {
    await createPresentation.mutateAsync(undefined);
    refetch();
  };

  const handleDeletePres = (id: string) => {
    return async () => {
      await deletePresentation.mutateAsync({ id });
      refetch();
    };
  };

  return (
    <>
      <Head>
        <title>Glides</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.containerOuter}>
        <div className={styles.containerInner}>
          <h1 className={styles.title}>Glides</h1>

          <button onClick={addPresentation}>Add presentation</button>

          <div className={styles.helloFrom}>
            <span>{data?.length} presentations</span>
            {data?.map((presentation) => (
              <div key={presentation.id}>
                Presentation {presentation.id}
                <button onClick={handleDeletePres(presentation.id)}>
                  Delete
                </button>
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
