name: CI/CD
on:
  push:
    branches:
      - master

jobs:
  db-migrate:
    name: Database Migration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run production migration
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
